// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolveX.Business.Assets.Integration.Context;

#nullable disable

namespace SolveX.Business.Assets.Integration.Migrations
{
    [DbContext(typeof(AssetContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("SolveX.Business.Assets.Domain.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("SolveX.Business.Assets.Domain.Models.AssetConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AssetConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
